operator:
  image:
    # operator.image.repository -- image repository
    repository: altinity/clickhouse-operator
    # operator.image.tag -- image tag (chart's appVersion value will be used if not set)
    tag: ""
    # operator.image.pullPolicy -- image pull policy
    pullPolicy: IfNotPresent
  # operator.resources -- custom resource configuration
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # operator.env -- additional environment variables for the deployment
  env: [ ]
  # - name: SAMPLE
  #   value: text
metrics:
  image:
    # metrics.image.repository -- image repository
    repository: altinity/metrics-exporter
    # metrics.image.tag -- image tag (chart's appVersion value will be used if not set)
    tag: ""
    # metrics.image.pullPolicy -- image pull policy
    pullPolicy: IfNotPresent
  # metrics.resources -- custom resource configuration
  resources: {}
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  # metrics.env -- additional environment variables for the deployment
  env: [ ]
  # - name: SAMPLE
  #   value: text

# imagePullSecrets -- image pull secret for private images
imagePullSecrets: []
# nameOverride -- override name of the chart
nameOverride: ""
# fullnameOverride -- full name of the chart.
fullnameOverride: ""

serviceAccount:
  # serviceAccount.create -- specifies whether a service account should be created
  create: true
  # serviceAccount.annotations -- annotations to add to the service account
  annotations: {}
  # serviceAccount.name -- the name of the service account to use; if not set and create is true, a name is generated using the fullname template
  name:

# nodeSelector -- node for scheduler pod assignment
nodeSelector: {}

# tolerations -- tolerations for scheduler pod assignment
tolerations: []

# affinity -- affinity for scheduler pod assignment
affinity: {}

serviceMonitor:
  # serviceMonitor.enabled -- ServiceMonitor CRD is created for a prometheus operator
  enabled: false
  # serviceMonitor.additionalLabels -- additional labels for service monitor
  additionalLabels: {}

# configs -- overrides operator default configmaps
configs:
  confdFiles: null
#    some-file: |
#      ...
  configdFiles: null
#    some-file: |
#      ...
  files: null
#    some-file: |
#      ...
  templatesdFiles: null
#    some-file: |
#      ...
  usersdFiles: null
#    some-file: |
#      ...

# additionalResources -- list of additional resources to create (are processed via `tpl` function)
additionalResources: [ ]
#  - |
#    apiVersion: v1
#    kind: ConfigMap
#    metadata:
#      name: {{ include "altinity-clickhouse-operator.fullname" . }}-cm
#      namespace: {{ .Release.Namespace }}
#  - |
#     apiVersion: v1
#     kind: Secret
#     metadata:
#       name: {{ include "altinity-clickhouse-operator.fullname" . }}-s
#       namespace: {{ .Release.Namespace }}
#     stringData:
#       mykey: my-value
