apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "docker-registry.fullname" . }}-cleanreg
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docker-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: cleanreg
  annotations:
    {{- toYaml .Values.cleanregCronJob.annotations | nindent 4 }}
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: {{ .Values.cleanregCronJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cleanregCronJob.failedJobsHistoryLimit }}
  schedule: {{ .Values.cleanregCronJob.schedule | quote }}
  jobTemplate:
    metadata:
      labels:
        {{- include "docker-registry.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: cleanreg
    spec:
      template:
        metadata:
          labels:
            {{- include "docker-registry.selectorLabels" . | nindent 12 }}
            app.kubernetes.io/component: cleanreg
          annotations:
            {{- toYaml .Values.cleanregCronJob.podAnnotations | nindent 12 }}
        spec:
          restartPolicy: {{ .Values.cleanregCronJob.restartPolicy }}
        {{- with .Values.cleanregCronJob.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "docker-registry.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.cleanregCronJob.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
          {{- with .Values.cleanregCronJob.args }}
              args:
                {{- toYaml . | nindent 16 }}
          {{- end }}
              securityContext:
                {{- toYaml .Values.cleanregCronJob.securityContext | nindent 16 }}
              image: "{{ .Values.cleanregCronJob.image.repository }}:{{ .Values.cleanregCronJob.image.tag }}"
              imagePullPolicy: {{ .Values.cleanregCronJob.image.pullPolicy }}
              resources:
                {{- toYaml .Values.cleanregCronJob.resources | nindent 16 }}
            {{- with .Values.cleanregCronJob.env }}
              env:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.cleanregCronJob.volumeMounts }}
              volumeMounts:
                {{- toYaml . | nindent 16 }}
            {{- end }}
        {{- with .Values.cleanregCronJob.volumes }}
          volumes:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
        {{- end }}
