{{- if eq .Values.kind "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "bazel-remote.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "bazel-remote.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "bazel-remote.selectorLabels" . | nindent 6 }}
  template:
    {{- include "bazel-remote.pod" . | nindent 4 }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
