apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "docker-registry-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docker-registry-ui.labels" . | nindent 4 }}
data:
  config.yml: |-
    {{- .Values.config | nindent 4 }}
