apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-registry-ui.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "docker-registry-ui.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "docker-registry-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "docker-registry-ui.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "docker-registry-ui.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ include "docker-registry-ui.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.containerPorts }}
          ports:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        {{- with .Values.env }}
          env:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          volumeMounts:
            - name: {{ include "docker-registry-ui.fullname" . }}
              mountPath: /opt/config.yml
              subPath: config.yml
        {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
        {{- end }}
      volumes:
        - name: {{ include "docker-registry-ui.fullname" . }}
          configMap:
            name: {{ include "docker-registry-ui.fullname" . }}
            items:
              - key: config.yml
                path: config.yml
                mode: 292 # 0444
    {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
