# Setup ClusterRoleBinding between ClusterRole and ServiceAccount.
# ClusterRoleBinding is namespace-less and must have unique name
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "altinity-clickhouse-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    clickhouse.altinity.com/chop: 0.19.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "altinity-clickhouse-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "altinity-clickhouse-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
