# Template Parameters:
#
# NAME=etc-clickhouse-operator-confd-files
# NAMESPACE=kube-system
# COMMENT=
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "altinity-clickhouse-operator.fullname" . }}-confd-files
  namespace: {{ .Release.Namespace }}
  labels:
    clickhouse.altinity.com/chop: 0.19.1
    {{- include "altinity-clickhouse-operator.labels" . | nindent 4 }}
data:
{{- if .Values.configs.confdFiles }}
  {{- toYaml .Values.configs.confdFiles | nindent 2 }}
{{ end }}
