apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab-runner.labels" . | nindent 4 }}
data:
  config.template.toml: |-
    {{- .Values.config | nindent 4 }}
