apiVersion: v1
kind: Service
metadata:
  name: {{ include "gitlab-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gitlab-runner.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "gitlab-runner.selectorLabels" . | nindent 4 }}
