apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
data:
  grafana-agent.yaml: |-
    {{ .Values.conf | nindent 4 }}
