apiVersion: v1
kind: Service
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    {{- include "grafana-agent.selectorLabels" . | nindent 4 }}
