{{- if eq .Values.workload.kind "statefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "grafana-agent.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.workload.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "grafana-agent.labels" . | nindent 4 }}
    {{- .Values.workload.labels | toYaml . | nindent 4 }}
spec:
  replicas: {{ .Values.workload.statefulSetSpec.replicas }}
{{- with .Values.workload.statefulSetSpec.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- with .Values.workload.statefulSetSpec.podManagementPolicy }}
  podManagementPolicy:
    {{- toYaml . | nindent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "grafana-agent.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "grafana-agent.fullname" . }}
  template:
    {{- include "grafana-agent.pod" . | nindent 4 }}
{{- with .Values.workload.statefulSetSpec.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
